CREATE TABLE IF NOT EXISTS TICK_SPECIES 
(
    SPECIES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SPECIES TEXT,
	LATIN TEXT,l
	IMAGE TEXT
);

CREATE TABLE IF NOT EXISTS TICKS 
(
    TICK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SPECIES_ID INTEGER NOT NULL,
	FOREIGN KEY (SPECIES_ID) REFERENCES TICK_SPECIES (SPECIES_ID)
);

CREATE TABLE IF NOT EXISTS LOCATION
(
    LOCATION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT
);

CREATE TABLE IF NOT EXISTS TICK_LOCATION
(
    TICK_LOCATION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TICK_ID INTEGER,
    LOCATION_ID INTEGER,
	SOURCE_ID INTEGER,
    DATE STRING,
	FOREIGN KEY (TICK_ID) REFERENCES TICKS (TICK_ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS TICK_LATIN_MAPPING
(
    TICK_LATIN_MAPPING_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TICK_NAME TEXT NOT NULL,
	TICK_LATIN_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TICK_SPECIES_INFO (
    SPECIES_INFO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SPECIES_ID INTEGER NOT NULL UNIQUE,
    BIO_CHARACTERISTIC TEXT,
    TYPICAL_HABITAT TEXT,
    HEALTH_RISKS TEXT,
    FOREIGN KEY (SPECIES_ID) REFERENCES TICK_SPECIES (SPECIES_ID)
);

CREATE TABLE IF NOT EXISTS AUTHENTICATION (
    AUTH_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	EMAIL TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	USERNAME TEXT NOT NULL
);
