import csv
import sqlite3

# Open Database
db = sqlite3.connect("ticks.db")
cursor = db.cursor()

ticks_mapping = {
    "Sheep tick": "Ixodes ricinus",
    "Fox tick": "Ixodes canisuga", 
    "Hedgehog tick": "Ixodes hexagonus",
    "Ornate cow tick": "Dermacentor reticulatus",
    "Southern rodent tick": "Ixodes acuminatus",
    "Marsh tick": "Ixodes apronophorus",
    "Tree-hole tick": "Ixodes arboricola",
    "Sand martin tick": "Ixodes lividus",
    "Vole tick": "Ixodes trianguliceps",
    "Pigeon tick": "Argas reflexus",
    "Long-legged bat tick": "Ixodes vespertilionis",
    "Natterer's bat tick": "Carios vespertilionis",
    "Cormorant tick": "Ixodes unicavatus",
    "Red sheep tick": "Haemaphysalis punctata",
    "Rabbit tick": "Haemaphysalis leporispalustris",
    "Squirrel tick": "Ixodes affinis",
    "Seabird tick": "Ixodes uriae",
    "Brown dog tick": "Rhipicephalus sanguineus",
    "Cattle tick": "Ixodes caledonicus",
    "Wood mouse tick": "Ixodes minor"
}

location_name_cache = {}

i = 0

with open("Tick Sightings - Y1.csv", encoding="UTF-8") as csv_file:
    for row in csv.DictReader(csv_file):
        tick_generate_id = row["id"]
        date = row["date"]
        location_name = row["location"]
        species_name = row["species"]
        latin_name = row["latinName"]

        #INSERT location name into LOCATION TABLE
        if (location_name not in location_name_cache):
            cursor.execute(
                "INSERT INTO LOCATION (NAME) VALUES (?)", (location_name,)
            )

            location_name_cache[location_name] = cursor.lastrowid

        location_id = location_name_cache[location_name]

        #INSERT the species name and latin name into TICK_SPECIES TABLE
        cursor.execute(
            "INSERT INTO TICK_SPECIES (SPECIES, LATIN) VALUES (?, ?)", (species_name, latin_name,)
        )

        #Get the ID autogenerated for the tick species we just inserted
        tick_species_id = cursor.lastrowid

        #INSERT the tick id into the link table TICKS
        cursor.execute(
            "INSERT INTO TICKS (SPECIES_ID) VALUES (?)", (tick_species_id,)
        )

        tick_id = cursor.lastrowid

        #INSERT the tick id, location id, source id, and date into the link table TICK_LOCATION
        cursor.execute(
            "INSERT INTO TICK_LOCATION (TICK_ID, LOCATION_ID, SOURCE_ID, DATE) VALUES (?, ?, ?, ?)", (tick_id, location_id, tick_generate_id, date,)
        )

    db.commit()
db.close()

print("FINISHED!!!!")